"""A Data Resource Object

Data Resources form the core of this API. Essentially, a data resource has four key components:

1. A resource name
2. A collection of API methods
3. A datastore name
4. A datastore schema

The resource name represents a unique name for the data resource (example: programs, providers, participants).

The collection of API methods represents the operations that can be performed on the datastore API resources
(i.e. GET, POST, PUT).

The datastore name is the name of the datastore (i.e. table) on physical storage.

The datastore schema represents the structure of the data resource and it's relationship to other data resources.
It is also used for validating any input made to that data resource.

Internally, data resources are converted into two distinct objects, one for representing the API resource and the other
for communicating with the database. Ideally, these two objects are automatically generated.

"""


class DataResource(object):
    """A Data Resource

    Attributes:
        data_resource_name (str): The name of the API resource.
        api_methods (dict): The API methods and associated configurations.
        table_name (str): The name of the datastore.
        table_schema (dict): The schema of the table for validation and generation.
        api_object (object): The API object generated by the data resource manager.
        datastore_object (object): The database ORM model generated by the data resource manager.

    """

    def __init__(self):
        self.data_resource_name = None
        self.api_methods = None
        self.table_name = None
        self.table_schema = None
        self.api_object = None
        self.datastore_object = None
        self.checksum = None
