"""Data Resource Manager

The Data Resource Manager manages the lifecycles of all data resources. It is responsible for
creating the Flask application that sits at the front of the data resource.

"""
import os
import json
import hashlib
from threading import Thread
from time import sleep
from flask import Flask
from flask_restful import Api, Resource
from data_resource_api.factories import ORMFactory, DataResourceFactory
from data_resource_api.config import ConfigurationFactory
from data_resource_api.db import engine, Base, Session, Checksum
from data_resource_api.logging import LogFactory
from data_resource_api.app.exception_handler import handle_errors
from data_resource_api.app.descriptor import (
    Descriptor,
    DescriptorFileHelper,
    DescriptorFromFile,
    DescriptorsGetter)
from data_resource_api.utils import exponential_backoff


class DataResource(object):
    """A Data Resource

    Attributes:
        data_resource_name (str): The name of the API resource.
        api_methods (dict): The API methods and associated configurations.
        table_name (str): The name of the datastore.
        table_schema (dict): The schema of the table for validation and generation.
        api_object (object): The API object generated by the data resource manager.
        datastore_object (object): The database ORM model generated by the data resource manager.

    """

    def __init__(self):
        self.data_resource_name = None
        self.data_resource_methods = None
        self.data_resource_object = None
        self.data_model_name = None
        self.data_model_schema = None
        self.data_model_object = None
        self.checksum = None
        self.model_checksum = None


class AvailableServicesResource(Resource):
    """A Flask resource for listing available services.

    Attributes:
        endpoints (list): The collection of endpoints known to the data resource.

    """

    def __init__(self):
        self.endpoints = []

    def add_endpoint(self, new_endpoint):
        self.endpoints.append(new_endpoint)

    def get(self):
        return {'endpoints': self.endpoints}, 200


class DataResourceManagerSync(object):
    """Data Resource Manager.

    Attributes:
        data_resource (list): A collection of all data resources managed by the data resouce manager.
        app_config (object): The application configuration object.

    """

    def __init__(self, descriptors: list = []):
        self.data_resources: DataResource = []
        self.app_config = ConfigurationFactory.from_env()
        self.app = None
        self.api = None
        self.available_services = AvailableServicesResource()
        self.orm_factory = ORMFactory(Base)
        self.data_resource_factory = DataResourceFactory()
        self.logger = LogFactory.get_console_logger('data-resource-manager')

        self.descriptor_directories = []
        self.descriptor_directories.append(self.get_data_resource_schema_path())
        self.custom_descriptors = descriptors

    def run(self):
        self.wait_for_db()
        # self.restore_models_from_database()

        while True:
            sleep_time = 10
            # sleep_time = self.get_sleep_interval()

            try:
                self.logger.info('Data Resource Manager Running...')
                self.logger.debug(f"Base metadata: {list(Base.metadata.tables.keys())}")
                self.monitor_data_models()
                
            except Exception as e:
                if e.code == 'e3q8':
                    self.logger.info("Waiting for DB...")
                    sleep(1)
                    continue

                self.logger.error(e)

            self.logger.info(f'Data Resource Manager Sleeping for {sleep_time} seconds...')
            sleep(sleep_time)

    def wait_for_db(self):
        db_active = False
        max_retries = 10
        retries = 0

        exponential_time = exponential_backoff(1, 1.5)

        while not db_active and retries <= max_retries:
            if retries != 0:
                sleep_time = exponential_time()
                self.logger.info(f'Sleeping for {sleep_time} with exponential backoff...')
                sleep(sleep_time)

            retries += 1

            self.logger.info('Checking database availability...')
            try:
                self.logger.info('Looking for DB...')
                session = Session()
                data = session.query(Checksum).all()
                db_active = True
                self.logger.info('Successfully connected to DB.')
            except Exception as e:
                self.logger.info('Hit exception looking for checksum...')
                # UndefinedTable
                if e.code == 'f405':
                    db_active = True
                    self.logger.info('Successfully connected to DB.')

                elif e.code == 'e3q8':
                    self.logger.info('Database is not available yet exception.')
                    self.logger.info(
                        'Waiting on database to become available.... {}/{}'.format(retries, max_retries))
                else:
                    self.logger.exception(f'Error occured upgrading database.')

        self.logger.info('Connected to DB.')

    # def restore_models_from_database(self) -> None:
    #     """This method will load all stored descriptor files from DB
    #     into SQL Alchemy ORM models.
    #     """
    #     # query database for all jsonb in checksum table
    #     json_descriptor_list = self.get_stored_descriptors()

    #     # load each item into our models
    #     for descriptor in json_descriptor_list:
    #         self.load_descriptor_into_sql_alchemy_model(descriptor)

    # def load_descriptor_into_sql_alchemy_model(self, descriptor: dict) -> None:
    #     desc = Descriptor(descriptor)
    #     table_schema = desc.table_schema
    #     table_name = desc.table_name
    #     api_schema = desc.api_schema

    #     data_model = self.orm_factory.create_orm_from_dict(
    #         table_schema, table_name, api_schema)

    # def get_stored_descriptors(self) -> list:
    #     """
    #     Gets stored json models from database.

    #     Returns:
    #         list: List of JSON dictionaries
    #     """
    #     session = Session()
    #     descriptor_list = []  # list of json dict
    #     try:
    #         query = session.query(Checksum)
    #         for _row in query.all():
    #             descriptor_list.append(_row.descriptor_json)
    #     except Exception as e:
    #         self.logger.exception('Error retrieving stored models')
    #     session.close()

    #     return descriptor_list

    def create_app(self):
        """Create the base Flask application.

        Returns:
            app (object): The Flask application context.

        """
        self.app = Flask(__name__)
        self.app.config.from_object(self.app_config)
        self.api = Api(self.app)
        self.api.add_resource(self.available_services,
                              '/', endpoint='all_services_ep')
        self.app.register_error_handler(Exception, handle_errors)

        return self.app

    def get_sleep_interval(self):
        """Retrieve the thread's sleep interval.

        Note:
            The method will look for an enviroment variable (SLEEP_INTERVAL).
            If the environment variable isn't set or cannot be parsed as an integer,
            the method returns the default interval of 30 seconds.

        Returns:
            int: The sleep interval (in seconds) for the thread.

        """

        return self.app_config.DATA_RESOURCE_SLEEP_INTERVAL

    def get_data_resource_schema_path(self):
        """Retrieve the path to look for data resource specifications.

        Returns:
            str: The search path for data resource schemas.

        Note:
            The application will look for an environment variable named DATA_RESOURCE_PATH
            and if it is not found will revert to the default path (i.e. /path/to/application/schema).

        """

        return os.getenv(
            'DATA_RESOURCE_PATH', os.path.join(self.app_config.ROOT_PATH, 'schema'))

    def data_resource_exists(self, data_resource_name):
        """Checks if a data resource is already registered with the data resource manager.

        Args:
            data_resource_name (str): Name of the data resource.

        Returns:
            bool: True if the data resource exists. False if not.

        """
        exists = False
        for data_resource in self.data_resources:
            if data_resource.data_resource_name.lower() == data_resource_name.lower():
                exists = True
                break
        return exists

    def data_resource_changed(self, data_resource_name, checksum):
        """Checks if the medata for a data model has been changed.

        Args:
            data_resource_name (str): Name of the data resource.
            checksum (str): Computed MD5 checksum of the data resource schema.

        Returns:
            bool: True if the data resource has been changed. False if not.

        """
        changed = False
        for data_resource in self.data_resources:
            if data_resource.data_resource_name.lower() == data_resource_name.lower():
                if data_resource.checksum != checksum:
                    changed = True
                break
        return changed

    def get_data_resource_index(self, data_resource_name):
        """Retrieves the index of a specific data resource in the data resources dict.

        Args:
           data_resource_name (str): Name of the data resource file on disk.

        Returns:
            int: Index of the data resource stored in memory, or -1 if not found.
        """
        index = -1
        for idx, data_resource in enumerate(self.data_resources):
            if data_resource.data_resource_name == data_resource_name.lower():
                index = idx
                break
        return index

    def get_model_checksum(self, table_name: str):
        """Retrieves a checksum by table name.

        Args:
            table_name (str): Name of the table to add the checksum.

        Returns:
            object: The checksum object if it exists, None otherwise.

        """
        session = Session()
        checksum = None
        try:
            checksum = session.query(Checksum).filter(
                Checksum.data_resource == table_name).first()
        except Exception as e:
            self.logger.error('Error retrieving checksum', exc_info=True)
        session.close()
        return checksum

    def monitor_data_models(self):
        """Wraps monitor data models for changes.

        Note:
            This method wraps the core worker for this class. This method has the
            responsbility of iterating through a directory to find schema files to load.
        """
        self.logger.info('Checking data models')

        descriptors = DescriptorsGetter(self.descriptor_directories, self.custom_descriptors)
        for descriptor in descriptors.iter_descriptors():
            self.process_descriptor(descriptor)

        self.logger.info('Completed check of data models')

    def process_descriptor(self, schema_dict: object):
        """Does data resource changes based on a given schema.
        """
        schema_filename = schema_dict.file_name
        self.logger.debug(f"Looking at {schema_filename}")

        try:
            # Extract data for easier use
            data_resource_name = schema_dict.data_resource_name
            table_name = schema_dict.table_name
            table_schema = schema_dict.table_schema
            api_schema = schema_dict.api_schema

            # calculate the checksum for this json
            data_resource_checksum = hashlib.md5(
                json.dumps(
                    table_schema,
                    sort_keys=True
                ).encode('utf-8')
            ).hexdigest()

            restricted_fields = schema_dict.restricted_fields

            if self.data_resource_exists(data_resource_name):

                # determine if api changed
                model = self.get_model_checksum(table_name)
                data_resource_index = self.get_data_resource_index(
                    data_resource_name)
                try:
                    if self.data_resource_changed(data_resource_name, data_resource_checksum):
                        data_resource = self.data_resources[data_resource_index]
                        data_resource.checksum = data_resource_checksum
                        data_resource.data_resource_methods = api_schema
                        data_resource.data_model_name = table_name
                        data_resource.data_model_schema = table_schema
                        data_resource.data_model_object = self.orm_factory.create_orm_from_dict(
                            table_schema, table_name, api_schema)
                        data_resource.model_checksum = self.get_model_checksum(
                            table_name)
                        data_resource.data_resource_object.data_model = data_resource.data_model_object
                        data_resource.data_resource_object.table_schema = table_schema
                        data_resource.data_resource_object.api_schema = api_schema
                        data_resource.data_resource_object.restricted_fields = restricted_fields
                        self.data_resources[data_resource_index] = data_resource
                except Exception as e:
                    self.logger.exception(
                        'Error checking data resource')
            else:
                data_resource = DataResource()
                data_resource.checksum = data_resource_checksum
                data_resource.data_resource_name = data_resource_name
                data_resource.data_resource_methods = api_schema
                data_resource.data_model_name = table_name
                data_resource.data_model_schema = table_schema
                data_resource.data_model_object = self.orm_factory.create_orm_from_dict(
                    table_schema, table_name, api_schema)
                data_resource.model_checksum = self.get_model_checksum(
                    table_name)
                data_resource.data_resource_object = self.data_resource_factory.create_api_from_dict(
                    api_schema, data_resource_name, table_name, self.api, data_resource.data_model_object, table_schema, restricted_fields)
                self.data_resources.append(data_resource)

        except Exception as e:
            self.logger.exception(f"Error loading schema '{schema_file}'")


class DataResourceManager(Thread, DataResourceManagerSync):
    def __init__(self):
        Thread.__init__(self)
        DataResourceManagerSync.__init__(self)

    def run(self):
        DataResourceManagerSync.run(self)
