#!/bin/bash

ORGANIZATION=brighthive
IMAGE_NAME=data-resource-api
VERSION_TAG=1.0.0
LATEST_TAG=latest
ECR_REPOSITORY_BASE=396527728813.dkr.ecr.us-east-2.amazonaws.com

# Build and tag image
docker build -t ${ORGANIZATION}/${IMAGE_NAME}:${VERSION_TAG} .
docker tag ${ORGANIZATION}/${IMAGE_NAME}:${VERSION_TAG} ${ECR_REPOSITORY_BASE}/${ORGANIZATION}/${IMAGE_NAME}:$LATEST_TAG
docker tag ${ORGANIZATION}/${IMAGE_NAME}:${VERSION_TAG} ${ECR_REPOSITORY_BASE}/${ORGANIZATION}/${IMAGE_NAME}:$VERSION_TAG

# Push image to ECR
docker push ${ECR_REPOSITORY_BASE}/${ORGANIZATION}/${IMAGE_NAME}:${LATEST_TAG}
docker push ${ECR_REPOSITORY_BASE}/${ORGANIZATION}/${IMAGE_NAME}:${VERSION_TAG}
